function hContourLevels = sortomatocontourlevels(~, ~, hSortomatoGraph, axesGraph)
    % SORTOMATOCONTOURLEVELS Specify contour levels
    %   Detailed explanation goes here
    
    %% Check for a contour levels figure.
    hContourLevels = getappdata(hSortomatoGraph, 'hContourLevels');
    if ~isempty(hContourLevels)
        figure(hContourLevels)
        return
    end % if
    
    %% Set the figure and font colors.
    if all(get(hSortomatoGraph, 'Color') == [0 0 0])
        bColor = 'k';
        bColorJava = java.awt.Color.black;
        fColor = 'w';
        fColorJava = java.awt.Color.white;

    else
        bColor = 'w';
        bColorJava = java.awt.Color.white;
        fColor = 'k';
        fColorJava = java.awt.Color.black;
        
    end % if
    
    %% Create the contour settings figure.
    % Create the figure.
    graphPosition = get(hSortomatoGraph, 'Position');
    
    guiWidth = 230;
    guiHeight = 257;
    guiPosition = [graphPosition(1) + 0.5*graphPosition(3) - guiWidth/2, ...
        graphPosition(2) + 0.5*graphPosition(4) - guiHeight/2, guiWidth, guiHeight];
    
%     hContourLevels = figure(...
%         'CloseRequestFcn', {@closerequestfcn, hSortomatoGraph}, ...
%         'Color', bColor, ...
%         'MenuBar', 'None', ...
%         'Name', 'Contour settings', ...
%         'NumberTitle', 'off', ...
%         'Position', guiPosition, ...
%         'Resize', 'off', ...
%         'Tag', 'hContourLevels');
    hContourLevels = figure(...
        'Color', bColor, ...
        'MenuBar', 'None', ...
        'Name', 'Contour settings', ...
        'NumberTitle', 'off', ...
        'Position', guiPosition, ...
        'Resize', 'off', ...
        'Tag', 'hContourLevels');
        
    % % Get the contour and plot data.
    hContour = getappdata(axesGraph, 'hContour');
    xyLocs = {get(hContour, 'XData') get(hContour, 'YData')};
    
    xData = getappdata(axesGraph, 'xData');
    yData = getappdata(axesGraph, 'yData');
    
    % % Create axes to display the contour levels.
    axesYLevels = axes(...
        'Box', 'On', ...
        'Color', 'None', ...
        'FontName', 'Arial', ...
        'FontSize', 11, ...
        'NextPlot', 'Add', ...
        'Parent', hContourLevels, ...
        'Tag', 'axesYLevels', ...
        'Units', 'Pixels', ...
        'XColor', fColor, ...
        'XLim', [xyLocs{2}(1) xyLocs{2}(end)], ...
        'XTick', [], ...
        'XTickLabel', {}, ...
        'YColor', fColor, ...
        'YLim', [xyLocs{2}(1) xyLocs{2}(end)], ...
        'YTick', [], ...
        'YTickLabel', {}, ...
        'ZColor', fColor);
    set(axesYLevels, 'Position', [10 20 210 100])
    
    axesXLevels = axes(...
        'Box', 'On', ...
        'Color', 'None', ...
        'FontName', 'Arial', ...
        'FontSize', 11, ...
        'NextPlot', 'Add', ...
        'Parent', hContourLevels, ...
        'Tag', 'axesXLevels', ...
        'Units', 'Pixels', ...
        'XColor', fColor, ...
        'XLim', [xyLocs{1}(1) xyLocs{1}(end)], ...
        'XTick', [], ...
        'XTickLabel', {}, ...
        'YColor', fColor, ...
        'YLim', [xyLocs{1}(1) xyLocs{1}(end)], ...
        'YTick', [], ...
        'YTickLabel', {}, ...
        'ZColor', fColor);
    set(axesXLevels, 'Position', [10 146 210 100])
    
    % % Plot the contour levels.
    plotXLevels = plot(...
        [xyLocs{1}(1) xyLocs{1}(end)], [xyLocs{1}(1) xyLocs{1}(end)], ...
        64, [1 0 0; 0 1 0], ...
        'LineWidth', 1, ...
        'Marker', 'o', ...
        'MarkerFaceColor', 'None', ...
        'Parent', axesXLevels);
    plotYLevels = scatter(...
        [xyLocs{2}(1) xyLocs{2}(end)], [xyLocs{2}(1) xyLocs{2}(end)], ...
        64, [1 0 0; 0 1 0], ...
        'LineWidth', 1, ...
        'Marker', 'o', ...
        'MarkerFaceColor', 'None', ...
        'Parent', axesYLevels);
    
    %% Construct and plot the data histograms.
    xFx = hist(xData, xyLocs{1});
    xFx = xFx/max(xFx)*xyLocs{1}(end);
    areaX = area(axesXLevels, xyLocs{1}, xFx);
    set(areaX, 'FaceColor', 'w')
    
    yFx = hist(yData, xyLocs{2});
    yFx = yFx/max(yFx)*xyLocs{2}(end);
    areaY = bar(axesYLevels, xyLocs{2}, yFx);
    set(areaY, 'FaceColor', 'w')
    
end % sortomatocontourlevels


function closerequestfcn(hObject, ~, hSortomatoGraph)
    % Close sortomato sub-GUIs
    %
    %
    
    %% Remove the GUI handle appdata and delete.
    rmappdata(hSortomatoGraph, 'hContourLevels')
    delete(hObject);
end % closerequestfcn