%   Description: Sort Surpass Spots and Surfaces using their statistical
%   properties. Does lots of other types of calculations and analyses.
%
%   <CustomTools>
%       <Menu>
%           <Submenu name="Surfaces Functions">
%               <Item name="Big Sortomato" icon="Matlab"
%                   tooltip="Analyze and sort Surpass objects based on their properties">
%                   <Command>MatlabXT::sortomato(%i)</Command>
%               </Item>
%           </Submenu>
%           <Submenu name="Spots Functions">
%               <Item name="Big Sortomato" icon="Matlab"
%                   tooltip="Analyze and sort Surpass objects based on their properties">
%                   <Command>MatlabXT::sortomato(%i)</Command>
%               </Item>
%           </Submenu>
%       </Menu>
%
%       <SurpassTab>
%           <SurpassComponent name="bpSurfaces">
%               <Item name="Big Sortomato" icon="Matlab"
%                   tooltip="Analyze and sort Surpass objects based on their properties">
%                   <Command>MatlabXT::sortomato(%i)</Command>
%               </Item>
%           </SurpassComponent>
%           <SurpassComponent name="bpSpots">
%               <Item name="Big Sortomato" icon="Matlab"
%                   tooltip="Analyze and sort Surpass objects based on their properties">
%                   <Command>MatlabXT::sortomato(%i)</Command>
%               </Item>
%           </SurpassComponent>
%       </SurpassTab>
%   </CustomTools>
% 
%   ©2010-2013, P. Beemiller. Licensed under a Creative Commmons Attribution
%   license. See: http://creativecommons.org/licenses/by/3.0/

function varargout = sortomato(xImarisID, varargin)
    % SORTOMATO Process and sort image objects from Imaris
    %   Syntax
    %   ------
    %   hGUI = SORTOMATO(xImarisID);
    %   hGUI = SORTOMATO(xImarisID, 'Color', 'k');   
    %   
    %   Description
    %   -----------
    %   hGUI = SORTOMATO(xImarisID) connects to the Imaris instance
    %   represented by the integer application ID xImarisID and creates a
    %   Sortomato figure. The handle to the figure is returned in hGUI.
    %   
    %   hGUI = SORTOMATO(xImarisID, 'Color', 'k') creates a Sortomato
    %   figure with a dark background.
    %
    %   The Sortomato is a GUI to perform analyses of segmented image
    %   objects (Spots or Surfaces) from Imaris, such as calculating
    %   mean-squared displacements, distances between objects, clustering
    %   of objects, and various other calculations. The statistical
    %   properties of the objects can also be used to create x-y plots to
    %   visually analyze the relationship between objects' derived image
    %   properties, and sort the objects into new groups based on
    %   statistical criteria.
    %   
    %   ©2010-2013, P. Beemiller. Licensed under a Creative Commmons Attribution
    %   license. See: http://creativecommons.org/licenses/by/3.0/
    warning('off', 'MATLAB:HandleGraphics:ObsoletedProperty:JavaFrame');
    %% Parse the inputs.
    sortomatoParser = inputParser;
    
    addRequired(sortomatoParser, 'xImarisID', ...
        @(arg)...
        (isnumeric(arg) && rem(arg, 1) == 0) || ...
        (~isnan(str2double(arg)) && rem(str2double(arg), 1) == 0))
    
    addParameter(sortomatoParser, 'Color', 'k', ...
        @(arg)any(strcmpi(arg, {'k', 'black', 'w', 'white'})))
    
    parse(sortomatoParser, xImarisID, varargin{:})
    
    %% Connect to the Imaris application and get the objects.
    xImarisApp = xtconnectimaris(xImarisID);
    surpassObjects = xtgetsporfaces(xImarisApp);
    
    if isempty(surpassObjects)
        return
    end % if
    
    %% Create the base figure.
    displayPos = get(0, 'MonitorPositions');
    guiWidth = 254;
    guiHeight = 240;
    guiPos = [...
        displayPos(1, 1) + displayPos(1, 3)/2 - guiWidth/2, ...
        displayPos(1, 2) + displayPos(1, 4)/2 - guiHeight/2, ...
        guiWidth, ...
        guiHeight];
    
    guiSortomato = figure(...
        'CloseRequestFcn', {@sortomatoclose}, ...
        'MenuBar', 'None', ...
        'Name', 'Sortomato', ...
        'NumberTitle', 'Off', ...
        'Position', guiPos, ...
        'Resize', 'off', ...
        'Tag', 'guiSortomato');
    
    % Setup the status bar.
    hStatus = statusbar(guiSortomato, '');
    hStatus.CornerGrip.setVisible(false)
    
    hStatus.ProgressBar.setForeground(java.awt.Color.black)
    hStatus.ProgressBar.setString('')
    hStatus.ProgressBar.setStringPainted(true)
    
    %% Load the cdata struct from disk and set the figure and font colors.
    switch sortomatoParser.Results.Color
        
        case 'k'
            sortomatoCData = load('sortomatoK_cdata.mat');
            set(guiSortomato, 'Color', 'k')
            bColor = 'k';
            fColor = 'w';
            
        case 'w'
            sortomatoCData = load('sortomato_cdata.mat');
            set(guiSortomato, 'Color', 'w')
            bColor = 'w';
            fColor = 'k';
            
    end % switch
    
    %% Create the graph type selection panel and new graph buttons.
    % Setup the GUI bottom to top.
    panelGraphType = uibuttongroup(...
        'BackgroundColor', bColor, ...
        'BorderType', 'Line', ...
        'BorderWidth', 1, ...
        'FontSize', 12, ...
        'ForegroundColor', fColor, ...
        'HighlightColor', fColor, ...
        'Parent', guiSortomato, ...
        'Position', [10 40 174 50]./[guiWidth guiHeight guiWidth guiHeight], ...
        'Tag', 'panelGraphType', ...
        'Title', 'Graph objects', ...
        'TitlePosition', 'CenterTop');
    
    uicontrol(...
        'BackgroundColor', bColor, ...
        'FontSize', 10, ...
        'ForegroundColor', fColor, ...
        'Parent', panelGraphType, ...
        'HorizontalAlign', 'Left', ...
        'Position', [10 8 80 21], ...
        'String', 'Singlets', ...
        'Style', 'radiobutton', ...
        'Tag', 'radioSinglets', ...
        'TooltipString', 'Select to graph single objects');
        
    uicontrol(...
        'BackgroundColor', bColor, ...
        'FontSize', 10, ...
        'ForegroundColor', fColor, ...
        'Parent', panelGraphType, ...
        'HorizontalAlign', 'Left', ...
        'Position', [97 8 60 21], ...
        'String', 'Tracks', ...
        'Style', 'radiobutton', ...
        'Tag', 'radioTracks', ...
        'TooltipString', 'Select to graph tracks');
        
    uicontrol(...
        'BackgroundColor', bColor, ...
        'CData', sortomatoCData.Graph, ...
        'Position', [190, 49, 24, 24], ...
        'String', '', ...
        'Style', 'pushbutton', ...
        'Tag', 'pushGraph', ...
        'TooltipString', 'Graph selected object statistics');
        
    uicontrol(...
        'BackgroundColor', bColor, ...
        'CData', sortomatoCData.Graph3, ...
        'Position', [220, 49, 24, 24], ...
        'String', '', ...
        'Style', 'pushbutton', ...
        'Tag', 'pushGraph3', ...
        'TooltipString', 'Graph selected object statistics in 3D');
        
    %% Create the Surpass object popup menu.
    % Label
    uicontrol(...
        'BackgroundColor', bColor, ...
        'FontSize', 12, ...
        'ForegroundColor', fColor, ...
        'HorizontalAlign', 'Left', ...
        'Parent', guiSortomato, ...
        'Position', [10 112 150 24], ...
        'String', 'Objects', ...
        'Style', 'text', ...
        'Tag', 'textObjects');
    
    % Popup
    popupObjects = uicontrol(...
        'BackgroundColor', bColor, ...
        'Callback', {@popupobjectscallback, guiSortomato}, ...
        'FontSize', 12, ...
        'ForegroundColor', [0.5 0.5 0.5], ...
        'Parent', guiSortomato, ...
        'Position', [84 116 100 24], ...
        'String', {surpassObjects.Name}, ...
        'Style', 'popupmenu', ...
        'Tag', 'popupObjects', ...
        'TooltipString', 'Select a Surpass object for plotting and sorting');
    
    % Refresh button
    uicontrol(...
        'BackgroundColor', bColor, ...
        'Callback', {@pushsurpassrefreshcallback, guiSortomato, popupObjects}, ...
        'CData', sortomatoCData.RefreshSurpass, ...
        'Parent', guiSortomato, ...
        'Position', [190, 114, 24, 24], ...
        'String', '', ...
        'Style', 'pushbutton', ...
        'Tag', 'pushSurpassRefresh', ...
        'TooltipString', 'Refresh the Surpass objects list');
    
    %% Create the processing function buttons.
    uicontrol(...
        'BackgroundColor', bColor, ...
        'Callback', {@sortomatocountpartners, guiSortomato}, ...
        'CData', sortomatoCData.Interactions, ...
        'Position', [10, 166, 24, 24], ...
        'String', '', ...
        'Style', 'pushbutton', ...
        'Tag', 'pushCountPartners', ...
        'TooltipString', 'Count interactions between Surfaces objects');
        
    uicontrol(...
        'BackgroundColor', bColor, ...
        'Callback', {@sortomatoflow, guiSortomato}, ...
        'CData', sortomatoCData.Flow, ...
        'Position', [40, 166, 24, 24], ...
        'String', '', ...
        'Style', 'pushbutton', ...
        'Tag', 'pushFlow', ...
        'TooltipString', 'Calculate directional movement toward a point');
        
    uicontrol(...
        'BackgroundColor', bColor, ...
        'Callback', {@sortomatosurfaceintensity, guiSortomato}, ...
        'CData', sortomatoCData.SurfaceIntensity, ...
        'Position', [70, 166, 24, 24], ...
        'String', '', ...
        'Style', 'pushbutton', ...
        'Tag', 'pushSurfaceIntensity', ...
        'TooltipString', 'Calculate surface and interior intensity');
        
    uicontrol(...
        'BackgroundColor', bColor, ...
        'Callback', {@sortomatodistances, guiSortomato}, ...
        'CData', sortomatoCData.Distances, ...
        'Position', [100, 166, 24, 24], ...
        'String', '', ...
        'Style', 'pushbutton', ...
        'Tag', 'pushDistances', ...
        'TooltipString', 'Calculate distances between objects');
        
    uicontrol(...
        'BackgroundColor', bColor, ...
        'Callback', {@sortomatoturningangles, guiSortomato}, ...
        'CData', sortomatoCData.TurningAngles, ...
        'Position', [130, 166, 24, 24], ...
        'String', '', ...
        'Style', 'pushbutton', ...
        'Tag', 'pushTurningAngles', ...
        'TooltipString', 'Calculate turning angles');
        
    uicontrol(...
        'BackgroundColor', bColor, ...
        'Callback', {@sortomatoarrest, guiSortomato}, ...
        'CData', sortomatoCData.Arrest, ...
        'Position', [160, 166, 24, 24], ...
        'String', '', ...
        'Style', 'pushbutton', ...
        'Tag', 'pushArrest', ...
        'TooltipString', 'Calculate track arrest coefficients');
        
    uicontrol(...
        'BackgroundColor', bColor, ...
        'Callback', {@sortomatomsd, guiSortomato}, ...
        'CData', sortomatoCData.MeanSquaredDisplacement, ...
        'Position', [10, 196, 24, 24], ...
        'String', '', ...
        'Style', 'pushbutton', ...
        'Tag', 'pushMeanSquaredDisplacement', ...
        'TooltipString', 'Calculate mean-squared displacements');
    
    uicontrol(...
        'BackgroundColor', bColor, ...
        'Callback', {@sortomatoscanefficiency, guiSortomato}, ...
        'CData', sortomatoCData.ScanEfficiency, ...
        'Position', [40, 196, 24, 24], ...
        'String', '', ...
        'Style', 'pushbutton', ...
        'Tag', 'pushScanEfficiency', ...
        'TooltipString', 'Calculate track scanning efficiencies');
    
    uicontrol(...
        'BackgroundColor', bColor, ...
        'Callback', {@sortomatoedgegrids, guiSortomato}, ...
        'CData', sortomatoCData.EdgeGrids, ...
        'Position', [70, 196, 24, 24], ...
        'String', '', ...
        'Style', 'pushbutton', ...
        'Tag', 'pushEdgeGrids', ...
        'TooltipString', 'Segment cell edges into grids and calculate local intensities', ...
        'UserData', sortomatoCData.RefreshChannels);
        
    uicontrol(...
        'BackgroundColor', bColor, ...
        'Callback', {@sortomatostatderivatives, guiSortomato}, ...
        'CData', sortomatoCData.StatDerivatives, ...
        'Position', [100, 196, 24, 24], ...
        'String', '', ...
        'Style', 'pushbutton', ...
        'Tag', 'pushStatDerivatives', ...
        'TooltipString', 'Calculate the derivatives of track statistics', ...
        'UserData', sortomatoCData.RefreshSurpass);
        
    uicontrol(...
        'BackgroundColor', bColor, ...
        'Callback', {@sortomatoclusteranalysis, guiSortomato}, ...
        'CData', sortomatoCData.ClusterAnalysis, ...
        'Position', [130, 196, 24, 24], ...
        'String', '', ...
        'Style', 'pushbutton', ...
        'Tag', 'pushClusterAnalysis', ...
        'TooltipString', 'Perform cluster analysis of objects');
        
    uicontrol(...
        'BackgroundColor', bColor, ...
        'Callback', {@sortomatocenteredtracks, guiSortomato}, ...
        'CData', sortomatoCData.CenteredTracks, ...
        'Position', [160, 196, 24, 24], ...
        'String', '', ...
        'Style', 'pushbutton', ...
        'Tag', 'pushCenteredPlots', ...
        'TooltipString', 'Plot centered object tracks');
        
    uicontrol(...
        'BackgroundColor', bColor, ...
        'CData', sortomatoCData.ExportStats, ...
        'Position', [220, 196, 24, 24], ...
        'String', '', ...
        'Style', 'pushbutton', ...
        'Tag', 'pushExportStats', ...
        'TooltipString', 'Export selected object track statistics');
    
    uicontrol(...
        'BackgroundColor', bColor, ...
        'CData', sortomatoCData.BinaryStatMath, ...
        'Position', [220, 166, 24, 24], ...
        'String', '', ...
        'Style', 'pushbutton', ...
        'Tag', 'pushStatMath', ...
        'TooltipString', 'Perform arithmetic using two statistics');

    %% Store the XT and Surpass objects.
    setappdata(guiSortomato, 'xImarisApp', xImarisApp)
    setappdata(popupObjects, 'surpassObjects', surpassObjects)
    
    %% Supress the constant data warning for contourf.
    warning('off', 'MATLAB:contourf:ConstantData')
    
    %% If the function call requested the figure handle, return it.
    if nargout == 1
        varargout{1} = guiSortomato;
    end % if
end % sortomatobase


function sortomatoclose(guiSortomato, ~)
    % SORTOMATOCLOSE Close request function for the Sortomato GUI
    %
    %
    
    %% Delete any graph's launched from the base.
    graphChildren = getappdata(guiSortomato, 'graphChildren');

    for c = 1:length(graphChildren)
        guiContourSettings = getappdata(graphChildren(c), 'guiContourSettings');
        if ishandle(guiContourSettings)
            delete(guiContourSettings)
        end % if

        guiLimits = getappdata(graphChildren(c), 'guiLimits');
        if ~isempty(guiLimits)
            delete(guiLimits)
        end % if

        guiView = getappdata(graphChildren(c), 'guiView');
        if ~isempty(guiView)
            delete(guiView)
        end % if

        delete(graphChildren(c))
    end % for c
    
    %% Delete any sub-GUIs launched from the base.
    guiChildren = getappdata(guiSortomato, 'guiChildren');
    
    if ~isempty(guiChildren)
        delete(guiChildren)
    end % if
    
    %% Restore the constant data warning for contourf.
    warning('on', 'MATLAB:contourf:ConstantData')
    
    %% Close the Sortomato figure.
    delete(guiSortomato)
end % sortomatoclose